### ISSUE TITLE
Csv not being populated- think selectors may have changed

### ISSUE THREAD

**Issue by alarrieux** [aarmora/jordan-scrapes-real-foreclose#2]
When running it for Hillsborough the csv is not being populated. When I run it for Miami Dade its actually incomplete. I tried to go through to see if I could update myself but was unsuccessful I know alot going on right now but if you get a chance to take a look would appreciate it.

-Ashley

**Comment by alarrieux** [comment]
Actually just checked selectors look the same. So now not sure why the output issue

**Comment by aarmora** [comment]
Hey @alarrieux. Thanks for reporting this. I'm not sure what exactly changed but I believe it should be working with my latest commit pushed today.

**Comment by alarrieux** [comment]
> Hey @alarrieux. Thanks for reporting this. I'm not sure what exactly changed but I believe it should be working with my latest commit pushed today.

nice, thank you. Will the new commit be reflected under the commit section? not seeing one from yesterday. Thanks for the work. Great job

**Comment by aarmora** [comment]
@alarrieux Somehow I missed this last comment. Did this ever get resolved for you?

**Comment by alarrieux** [comment]
> missed
@aarmora  no worries, I am trying to pull it together using python. But the code last I tried didn't work.

**Comment by aarmora** [comment]
@alarrieux I've since updated the code and tested it with Hillsborough. If you give it a try, let me know if it resolves your problem.

Thanks.
